version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  api:
    build:
      context: .
      dockerfile: api/Dockerfile.api
    container_name: api
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/code/api
      - ./utils:/code/utils

  job_ingestor:
    build:
      context: .
      dockerfile: job_ingestor/Dockerfile.ingestor
    container_name: ingestor
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code
    volumes:
      - ./job_ingestor:/code/job_ingestor
      - ./utils:/code/utils
    command: ["sleep", "infinity"] # keeps container running, you exec into it to trigger ingestion

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000" # localhost:3000 -> nginx inside container
    volumes:
      - ./frontend:/app           # Mount source code
      - /app/node_modules         # Avoid overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Required for file watching inside Docker
    command: npm run dev -- --host  # Run vite in dev mode, listen on all hosts

volumes:
  postgres_data: