FROM python:3.11-slim

WORKDIR /code

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./job_ingestor /code/job_ingestor
COPY ./utils /code/utils

# Default: container sleeps, you run ingestion when needed
CMD ["sleep", "infinity"]